# Generated by Django 4.1 on 2022-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(blank=True, max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
