# Generated by Django 4.1 on 2022-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_database_first_database_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
