# Generated by Django 4.1 on 2022-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_alter_database_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
