# Generated by Django 4.1 on 2022-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_remove_database_email_database_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='password',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
