# Generated by Django 4.1 on 2022-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_database_password_alter_database_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
